// <auto-generated />
using System;
using ExampleProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExampleProject.Migrations
{
    [DbContext(typeof(NpgsqlContext))]
    [Migration("20230426225545_InitialPostgresMigration")]
    partial class InitialPostgresMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExampleProject.AbstractSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ExampleProject.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ExampleProject.PlayerToSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SkillId");

                    b.ToTable("PlayerToSkill");
                });

            modelBuilder.Entity("ExampleProject.MagicSkill", b =>
                {
                    b.HasBaseType("ExampleProject.AbstractSkill");

                    b.Property<string>("RunicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("MagicSkills");
                });

            modelBuilder.Entity("ExampleProject.MartialSkill", b =>
                {
                    b.HasBaseType("ExampleProject.AbstractSkill");

                    b.Property<bool>("HasStrike")
                        .HasColumnType("boolean");

                    b.ToTable("MartialSkills");
                });

            modelBuilder.Entity("ExampleProject.PlayerToSkill", b =>
                {
                    b.HasOne("ExampleProject.Player", "Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExampleProject.AbstractSkill", "Skill")
                        .WithMany("PlayersWithSkill")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ExampleProject.AbstractSkill", b =>
                {
                    b.Navigation("PlayersWithSkill");
                });

            modelBuilder.Entity("ExampleProject.Player", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
